version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db_docker_symfony_prod
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3305"
    volumes:
      - my-db:/var/lib/prod/mysql
    networks:
      - prod

  www:
    build: Docker/prod
    container_name: www_docker_php_prod
    ports:
      - "80:80"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./Docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - prod

networks:
  prod:

volumes:
  my-db:
